services:
  websocket-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: websocket-server
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - socket-network
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:latest
    container_name: socket-server-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: messages
      MYSQL_USER: socket
      TZ: America/New_York
    ports:
        - "3306:3306"
    networks:
        - socket-network
    volumes:
        - mysql-data:/var/lib/mysql
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: on-failure:3

networks:
  socket-network:
    driver: bridge
    name: socket-network

volumes:
  mysql-data:
